//------------------------------------------------------------------------------
// <auto-generated>
//      Este código fue generado por una herramienta.
//
//      Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebSOAP
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ws/", ConfigurationName = "ServicioWebSOAP.WSOperaciones")]
    public interface WSOperaciones
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://ws/WSOperaciones/ProcesarPagoRequest", ReplyAction = "http://ws/WSOperaciones/ProcesarPagoResponse")]
        System.Threading.Tasks.Task<ServicioWebSOAP.ProcesarPagoResponse> ProcesarPagoAsync(ServicioWebSOAP.ProcesarPagoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws/WSOperaciones/LoginRequest", ReplyAction = "http://ws/WSOperaciones/LoginResponse")]
        System.Threading.Tasks.Task<ServicioWebSOAP.LoginResponse> LoginAsync(ServicioWebSOAP.LoginRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ProcesarPago", WrapperNamespace = "http://ws/", IsWrapped = true)]
    public partial class ProcesarPagoRequest
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int total;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public int pago;

        public ProcesarPagoRequest()
        {
        }

        public ProcesarPagoRequest(int total, int pago)
        {
            this.total = total;
            this.pago = pago;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ProcesarPagoResponse", WrapperNamespace = "http://ws/", IsWrapped = true)]
    public partial class ProcesarPagoResponse
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int @return;

        public ProcesarPagoResponse()
        {
        }

        public ProcesarPagoResponse(int @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LoginRequest
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Login", Namespace = "http://ws/", Order = 0)]
        public ServicioWebSOAP.LoginRequestBody Body;

        public LoginRequest()
        {
        }

        public LoginRequest(ServicioWebSOAP.LoginRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class LoginRequestBody
    {
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string usuario;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string contrasena;

        public LoginRequestBody()
        {
        }

        public LoginRequestBody(string usuario, string contrasena)
        {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LoginResponse
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "LoginResponse", Namespace = "http://ws/", Order = 0)]
        public ServicioWebSOAP.LoginResponseBody Body;

        public LoginResponse()
        {
        }

        public LoginResponse(ServicioWebSOAP.LoginResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class LoginResponseBody
    {
        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public bool @return;

        public LoginResponseBody()
        {
        }

        public LoginResponseBody(bool @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WSOperacionesChannel : ServicioWebSOAP.WSOperaciones, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WSOperacionesClient : System.ServiceModel.ClientBase<ServicioWebSOAP.WSOperaciones>, ServicioWebSOAP.WSOperaciones
    {
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public WSOperacionesClient() :
                base(WSOperacionesClient.GetDefaultBinding(), WSOperacionesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSOperacionesPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WSOperacionesClient(EndpointConfiguration endpointConfiguration) :
                base(WSOperacionesClient.GetBindingForEndpoint(endpointConfiguration), WSOperacionesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WSOperacionesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(WSOperacionesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WSOperacionesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(WSOperacionesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WSOperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<ServicioWebSOAP.ProcesarPagoResponse> ProcesarPagoAsync(ServicioWebSOAP.ProcesarPagoRequest request)
        {
            return base.Channel.ProcesarPagoAsync(request);
        }

        public System.Threading.Tasks.Task<ServicioWebSOAP.LoginResponse> LoginAsync(ServicioWebSOAP.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }

        public bool Login(string usuario, string contrasena)
        {
            var cuerpo = new ServicioWebSOAP.LoginRequestBody(usuario, contrasena);
            var peticion = new ServicioWebSOAP.LoginRequest(cuerpo);

            var tarea = this.LoginAsync(peticion);
            var respuesta = tarea.GetAwaiter().GetResult();

            if (respuesta != null && respuesta.Body != null)
            {
                return respuesta.Body.@return;
            }
            return false;
        }

        public int ProcesarPago(int total, int pago)
        {
            var peticion = new ServicioWebSOAP.ProcesarPagoRequest(total, pago);

            var tarea = this.ProcesarPagoAsync(peticion);
            var respuesta = tarea.GetAwaiter().GetResult();

            if (respuesta != null)
            {
                return respuesta.@return;
            }
            return -1; 
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSOperacionesPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSOperacionesPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ServicioWeb_SOAP/WSOperaciones");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSOperacionesClient.GetBindingForEndpoint(EndpointConfiguration.WSOperacionesPort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSOperacionesClient.GetEndpointAddress(EndpointConfiguration.WSOperacionesPort);
        }

        public enum EndpointConfiguration
        {
            WSOperacionesPort,
        }
    }
}